"""
POST /api/export       — 导出为 .py 文件（旧接口，保留兼容）
POST /api/export-notebook — 导出为 .ipynb Jupyter Notebook（推荐）

导出模块支持两种格式：
- .py: 纯 Python 源码文件
- .ipynb: Jupyter Notebook，按 import / class / main 拆分为多个 cell
"""
from fastapi import APIRouter
from pydantic import BaseModel
import base64
import nbformat
from nbformat.v4 import new_notebook, new_code_cell, new_markdown_cell

from backend.services.codegen_facade import generate_full

router = APIRouter()


class ExportRequest(BaseModel):
    """
    代码导出请求（已有代码字符串）

    Attributes:
        code: 完整的 Python 代码字符串
        format: 导出格式，"py" 或 "ipynb"（默认 "py"）
        filename: 导出文件名（不含扩展名）
    """
    code: str
    format: str = "py"  # "py" or "ipynb"
    filename: str = "flowhamster_model"


class ExportResponse(BaseModel):
    """
    导出响应

    Attributes:
        success: 是否成功导出
        content: 文件内容的 base64 编码字符串
        filename: 建议的文件名（含正确扩展名）
        mime_type: MIME 类型（text/x-python 或 application/x-ipynb+json）
    """
    success: bool
    content: str  # base64 encoded
    filename: str
    mime_type: str


# ── helpers ──────────────────────────────────────────────────────────────────

def _split_code_into_cells(code: str) -> list[str]:
    """
    将统一代码生成器输出的完整脚本拆分为多个代码 cell。
    
    典型输出结构：
        # Generated by FlowHamster
        # DO NOT EDIT ...
        import torch
        import torch.nn as nn

        class FlowHamsterModel(nn.Module):
            ...

        if __name__ == "__main__":
            model = FlowHamsterModel()
            print(model)

    划分策略：
        Cell 1 – import 语句（含注释头）
        Cell 2 – class FlowHamsterModel 定义（不含 if __name__）
        Cell 3 – if __name__ 块（实例化 + print）
    """
    cells = []

    # 1. 头部注释 + import
    import_end = code.find("class FlowHamsterModel")
    if import_end == -1:
        import_end = 0
    import_block = code[:import_end].rstrip()
    if import_block:
        cells.append(import_block)

    # 2. class 定义
    class_start = code.find("class FlowHamsterModel")
    if_start = code.find("if __name__", class_start)
    if if_start == -1:
        class_block = code[class_start:].rstrip()
    else:
        class_block = code[class_start:if_start].rstrip()
    if class_block:
        cells.append(class_block)

    # 3. if __name__ 块（实例化 + print）
    if if_start != -1:
        main_block = code[if_start:].rstrip()
        cells.append(main_block)

    return cells if cells else [code]


def _build_notebook(cells_source: list[str]) -> str:
    """根据代码段列表构建 Jupyter Notebook。"""
    nb = new_notebook()
    nb.cells = [
        new_markdown_cell("# FlowHamster Generated Model\n\nGenerated by FlowHamster — Neural Network Editor"),
    ]
    for src in cells_source:
        nb.cells.append(new_code_cell(src))

    # 添加 kernelspec metadata
    nb.metadata.setdefault("kernelspec", {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    })
    nb.metadata.setdefault("language_info", {
        "name": "python",
        "version": "3.10.0",
    })
    return nbformat.writes(nb)


# ── routes ────────────────────────────────────────────────────────────────────

@router.post("/export", response_model=ExportResponse)
async def export_code(req: ExportRequest):
    """
    将已有代码导出为文件。

    支持 .py 和 .ipynb 两种格式。
    返回 base64 编码的文件内容。

    Returns:
        ExportResponse: 包含 base64 编码的文件内容
    """
    if req.format == "ipynb":
        cells = _split_code_into_cells(req.code)
        content = _build_notebook(cells)
        mime = "application/x-ipynb+json"
        filename = f"{req.filename}.ipynb"
    else:
        content = req.code
        mime = "text/x-python"
        filename = f"{req.filename}.py"

    b64 = base64.b64encode(content.encode()).decode()

    return ExportResponse(
        success=True,
        content=b64,
        filename=filename,
        mime_type=mime,
    )


class NotebookExportRequest(BaseModel):
    """
    导出为 Jupyter Notebook 的请求

    与 /export 不同，这里接收前端 flow JSON，后端负责代码生成。

    Attributes:
        graph: 前端 flow_json（nodes + edges）
        filename: 导出文件名（不含扩展名）
        training_config: 可选，训练配置
        data_graph: 可选，数据流图
        bindings: 可选，输入输出绑定
    """
    graph: dict          # 前端 flow_json（nodes + edges）
    filename: str = "flowhamster_model"
    training_config: dict | None = None
    data_graph: dict | None = None
    bindings: list[dict] | None = None


def _build_workflow_scaffold(data_graph: dict | None, bindings: list[dict] | None, training_config: dict | None) -> str:
    """构建数据流相关的 Python scaffold"""
    if not data_graph and not bindings:
        return ""

    from backend.services.dataflow_compiler import compile_dataflow

    compiled = compile_dataflow(
        model_graph=None,
        data_graph=data_graph,
        bindings=bindings,
        training_config=training_config,
    )

    if not compiled.has_workflow_runtime:
        return ""

    return f"\n\n{compiled.python_scaffold}\n"


@router.post("/export-notebook", response_model=ExportResponse)
async def export_notebook(req: NotebookExportRequest):
    """
    推荐接口：前端直接传 graph JSON，后端负责代码生成 + cell 划分。

    生成的 notebook 包含以下 cell：
    1. Markdown 头部说明
    2. Import 语句
    3. FlowHamsterModel 类定义
    4. if __name__ == "__main__" 块（实例化和 print）

    支持 data_graph 和 bindings 参数，会追加数据流相关的 scaffold。

    Returns:
        ExportResponse: base64 编码的 .ipynb 文件内容
    """
    try:
        # 1. 用统一代码生成器生成完整代码
        options = {"training_config": req.training_config} if req.training_config is not None else None
        code = generate_full(req.graph, options=options)

        # 2. 如果有 data_graph 或 bindings，追加数据流 scaffold
        workflow_scaffold = _build_workflow_scaffold(
            req.data_graph,
            req.bindings,
            req.training_config
        )
        if workflow_scaffold:
            code += workflow_scaffold

        # 3. 拆分为多个 cell
        cells = _split_code_into_cells(code)

        # 4. 构建 notebook
        content = _build_notebook(cells)
        b64 = base64.b64encode(content.encode()).decode()

        return ExportResponse(
            success=True,
            content=b64,
            filename=f"{req.filename}.ipynb",
            mime_type="application/x-ipynb+json",
        )
    except Exception as e:
        # 出错时返回可读的错误 notebook
        error_nb = new_notebook()
        error_nb.cells = [
            new_markdown_cell(f"# FlowHamster Export Error\n\n`{e}`"),
            new_code_cell(f"raise RuntimeError({str(e)!r})"),
        ]
        content = nbformat.writes(error_nb)
        b64 = base64.b64encode(content.encode()).decode()
        return ExportResponse(
            success=False,
            content=b64,
            filename=f"{req.filename}.ipynb",
            mime_type="application/x-ipynb+json",
        )
