"""
FlowHamster 代码生成核心服务
将前端传来的 React Flow 图结构转换为可运行的 PyTorch nn.Module 代码
支持每条边的 mergeMode（concat / add / mul / stack）
"""
from collections import deque

# Merge mode -> forward line template
MERGE_TEMPLATES = {
    'concat': lambda srcs, dim: f"torch.cat([{', '.join(srcs)}], dim={dim})",
    'add':    lambda srcs, dim: f"({' + '.join(srcs)})",
    'mul':    lambda srcs, dim: f"({' * '.join(srcs)})",
    'stack':  lambda srcs, dim: f"torch.stack([{', '.join(srcs)}], dim={dim})",
}

# 模块代码模板（按节点类型）
MODULE_TEMPLATES = {
    "conv2d": lambda p: f"nn.Conv2d(in_channels={p['in_channels']}, out_channels={p['out_channels']}, kernel_size={p['kernel_size']}, stride={p['stride']}, padding={p['padding']}, bias={p['bias']})",
    "conv1d": lambda p: f"nn.Conv1d(in_channels={p['in_channels']}, out_channels={p['out_channels']}, kernel_size={p['kernel_size']}, stride={p['stride']}, padding={p['padding']}, bias={p['bias']})",
    "conv3d": lambda p: f"nn.Conv3d(in_channels={p['in_channels']}, out_channels={p['out_channels']}, kernel_size={p['kernel_size']}, stride={p['stride']}, padding={p['padding']}, bias={p['bias']})",
    "linear": lambda p: f"nn.Linear(in_features={p['in_features']}, out_features={p['out_features']}, bias={p['bias']})",
    "relu": lambda _: "nn.ReLU()",
    "gelu": lambda _: "nn.GELU()",
    "silu": lambda _: "nn.SiLU()",
    "sigmoid": lambda _: "nn.Sigmoid()",
    "tanh": lambda _: "nn.Tanh()",
    "leakyrelu": lambda p: f"nn.LeakyReLU(negative_slope={p.get('negative_slope', 0.01)})",
    "maxpool": lambda p: f"nn.MaxPool2d(kernel_size={p.get('kernel_size', 2)}, stride={p.get('stride', 2)})",
    "avgpool": lambda p: f"nn.AvgPool2d(kernel_size={p.get('kernel_size', 2)}, stride={p.get('stride', 2)})",
    "adaptiveavgpool": lambda p: f"nn.AdaptiveAvgPool2d(output_size={p.get('output_size', 1)})",
    "globalavgpool": lambda _: "nn.AdaptiveAvgPool2d(1)",
    "batchnorm": lambda p: f"nn.BatchNorm2d(num_features={p['num_features']})",
    "layernorm": lambda p: f"nn.LayerNorm(normalized_shape={p.get('normalized_shape', 'C')})",
    "groupnorm": lambda p: f"nn.GroupNorm(num_groups={p['num_groups']}, num_channels={p['num_channels']})",
    "dropout": lambda p: f"nn.Dropout(p={p.get('p', 0.5)}, inplace=True)",
    "flatten": lambda p: f"nn.Flatten(start_dim={p.get('start_dim', 1)})",
    "softmax": lambda p: f"nn.Softmax(dim={p.get('dim', -1)})",
    "embedding": lambda p: f"nn.Embedding(num_embeddings={p['num_embeddings']}, embedding_dim={p['embedding_dim']})",
    "crossentropyloss": lambda _: "nn.CrossEntropyLoss()",
    "mseloss": lambda _: "nn.MSELoss()",
    "adam": lambda p: f"optim.Adam(lr={p.get('lr', 0.001)}, betas={p.get('betas', '(0.9, 0.999)')}, eps={p.get('eps', 1e-8)}, weight_decay={p.get('weight_decay', 0)})",
    "adamw": lambda p: f"optim.AdamW(lr={p.get('lr', 0.001)}, betas={p.get('betas', '(0.9, 0.999)')}, eps={p.get('eps', 1e-8)}, weight_decay={p.get('weight_decay', 0.01)})",
    "sgd": lambda p: f"optim.SGD(lr={p.get('lr', 0.01)}, momentum={p.get('momentum', 0.9)}, weight_decay={p.get('weight_decay', 0)})",
    "rmsprop": lambda p: f"optim.RMSprop(lr={p.get('lr', 0.001)}, alpha={p.get('alpha', 0.99)}, eps={p.get('eps', 1e-8)})",
}


class GraphCodeGenerator:
    def __init__(self, graph: dict, options: dict = None):
        self.graph = graph
        self.options = options or {}
        self.warnings: list[str] = []
        self.nodes = {n["id"]: n for n in graph.get("nodes", [])}
        self.edges = graph.get("edges", [])
        self.module_cache: dict = {}
        self.module_vars: dict = {}  # node_id -> var_name

    def generate(self) -> str:
        """主入口：生成完整 PyTorch 模型代码"""
        if not self.nodes:
            return "# Empty graph — add nodes from the sidebar"

        sorted_nodes = self._topological_sort()
        self._assign_module_vars(sorted_nodes)

        init_parts = []
        for node in sorted_nodes:
            if node["data"].get("nodeType") in ("input", "output"):
                continue
            var = self.module_vars.get(node["id"])
            if not var:
                continue
            code = self._generate_module_code(node)
            if code:
                init_parts.append(f"        {var} = {code}")

        forward_lines = []
        for node in sorted_nodes:
            line = self._generate_forward_line(node)
            if line:
                forward_lines.append(f"        {line}")

        include_trainer = self.options.get("include_trainer", False)
        trainer_code = self._generate_trainer() if include_trainer else ""

        return f"""# Generated by FlowHamster
# DO NOT EDIT — Regenerated from graph editor
import torch
import torch.nn as nn
import torch.optim as optim

class FlowHamsterModel(nn.Module):
    def __init__(self):
        super().__init__()
{chr(10).join(init_parts) if init_parts else '        pass'}

    def forward(self, x):
{chr(10).join(forward_lines)}

if __name__ == "__main__":
    model = FlowHamsterModel()
    x = torch.randn(1, {self._guess_input_channels()})
    print(model)
    print(model(x).shape)
{trainer_code}
"""

    def _topological_sort(self):
        """Kahn 算法拓扑排序"""
        in_degree = {nid: 0 for nid in self.nodes}
        adj = {nid: [] for nid in self.nodes}
        for edge in self.edges:
            src, tgt = edge["source"], edge["target"]
            if src in in_degree and tgt in in_degree:
                in_degree[tgt] += 1
                adj[src].append(tgt)

        queue = deque([nid for nid, d in in_degree.items() if d == 0])
        sorted_list = []
        while queue:
            nid = queue.popleft()
            sorted_list.append(self.nodes[nid])
            for nb in adj[nid]:
                in_degree[nb] -= 1
                if in_degree[nb] == 0:
                    queue.append(nb)

        if len(sorted_list) != len(self.nodes):
            self.warnings.append("Warning: graph contains cycles — some nodes may be unreachable")
        return sorted_list

    def _assign_module_vars(self, sorted_nodes):
        """为每个节点分配模块变量名（带复用检测）"""
        for node in sorted_nodes:
            ntype = node["data"].get("nodeType", "")
            params = node["data"].get("params", {})
            if ntype in ("input", "output"):
                continue
            key = (ntype, tuple(sorted(params.items())))
            if key in self.module_cache:
                self.module_vars[node["id"]] = self.module_cache[key]
            else:
                safe_id = node["id"].replace("-", "_").replace(":", "_")
                var_name = f"self.{ntype}_{safe_id}"
                self.module_vars[node["id"]] = var_name
                self.module_cache[key] = var_name

    def _generate_module_code(self, node) -> str:
        ntype = node["data"].get("nodeType", "")
        params = node["data"].get("params", {})
        if ntype in MODULE_TEMPLATES:
            return MODULE_TEMPLATES[ntype](params)
        # add/mul/concat handled in forward
        self.warnings.append(f"Unknown node type: {ntype}")
        return None

    def _generate_forward_line(self, node) -> str:
        ntype = node["data"].get("nodeType", "")
        nid = node["id"]

        if ntype == "input":
            return None
        if ntype == "output":
            return "return x"

        in_edges = [e for e in self.edges if e["target"] == nid]
        if not in_edges:
            return None

        var = self.module_vars.get(nid)
        # Node with module (conv, linear, etc.)
        if var:
            return f"x = {var}(x)"

        # Merge nodes — use merge mode from edge data
        if ntype in ("add", "mul", "concat"):
            # Get merge mode from edge data, fallback to node type
            merge_modes = [e.get("data", {}).get("mergeMode", "concat") if isinstance(e.get("data"), dict) else "concat" for e in in_edges]
            # Group by merge mode
            if len(in_edges) == 1:
                src_var = self.module_vars.get(in_edges[0]["source"], "x")
                return f"x = {src_var}"
            # All same mode: merge all inputs
            mode = merge_modes[0]
            src_vars = [self.module_vars.get(e["source"], "x") for e in in_edges]
            dim = node["data"]["params"].get("dim", 1)
            if mode in MERGE_TEMPLATES:
                return f"x = {MERGE_TEMPLATES[mode](src_vars, dim)}"
            # Fallback
            return f"x = {MERGE_TEMPLATES['concat'](src_vars, dim)}"

        return None

    def _guess_input_channels(self) -> str:
        for node in self.graph.get("nodes", []):
            if node["data"].get("nodeType") == "input":
                shape = node["data"]["params"].get("shape", "3, 224, 224")
                return shape.split(",")[0].strip() if "," in shape else "3"
        return "3"

    def _generate_trainer(self) -> str:
        opt = self.options.get("optimizer", "Adam")
        loss = self.options.get("loss_function", "CrossEntropyLoss")
        lr = self.options.get("lr", 0.001)
        epochs = self.options.get("epochs", 10)
        return f"""
# === Trainer Scaffold ===
optimizer = optim.{opt}(model.parameters(), lr={lr})
criterion = nn.{loss}()

for epoch in range({epochs}):
    model.train()
    # TODO: add your training loop here
    print(f"Epoch {{epoch+1}}/{epochs} - implement data loading and training logic")
"""
