"""
Export route contract tests
验证 /api/export 和 /api/export-notebook 的响应契约。
"""
import base64
import json
import pytest
from fastapi.testclient import TestClient

from backend.main import app

client = TestClient(app)

SAMPLE_CODE = """# Generated by FlowHamster
# DO NOT EDIT -- Regenerated from graph editor
import torch
import torch.nn as nn

class FlowHamsterModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.x_linear_1 = nn.Linear(in_features=10, out_features=20, bias=True)

    def forward(self, x):
        x_linear_1 = self.x_linear_1(x)
        return x_linear_1


if __name__ == "__main__":
    model = FlowHamsterModel()
    print(model)
"""


def test_export_py_returns_base64_with_correct_mime():
    """POST /api/export format=py 返回 base64 编码的 .py 文件，MIME 类型正确"""
    response = client.post(
        "/api/export",
        json={
            "code": SAMPLE_CODE,
            "format": "py",
            "filename": "test_model",
        },
    )
    assert response.status_code == 200
    data = response.json()
    assert data["success"] is True
    assert data["filename"] == "test_model.py"
    assert data["mime_type"] == "text/x-python"

    # 验证 base64 解码后内容一致
    decoded = base64.b64decode(data["content"]).decode("utf-8")
    assert decoded == SAMPLE_CODE


def test_export_ipynb_returns_valid_notebook():
    """POST /api/export format=ipynb 返回有效的 notebook JSON，cell 拆分符合预期"""
    response = client.post(
        "/api/export",
        json={
            "code": SAMPLE_CODE,
            "format": "ipynb",
            "filename": "test_model",
        },
    )
    assert response.status_code == 200
    data = response.json()
    assert data["success"] is True
    assert data["filename"] == "test_model.ipynb"
    assert data["mime_type"] == "application/x-ipynb+json"

    # 解码并验证 notebook 结构
    decoded = base64.b64decode(data["content"]).decode("utf-8")
    notebook = json.loads(decoded)
    assert notebook["nbformat"] >= 4
    cells = notebook["cells"]
    assert len(cells) >= 3  # markdown + at least 2 code cells

    # Cell 0 应为 markdown
    assert cells[0]["cell_type"] == "markdown"
    assert "FlowHamster" in cells[0]["source"][0]

    # 应有 import cell
    import_cell = next((c for c in cells if c["cell_type"] == "code" and "import torch" in "".join(c["source"])), None)
    assert import_cell is not None

    # 应有 class 定义 cell
    class_cell = next((c for c in cells if c["cell_type"] == "code" and "class FlowHamsterModel" in "".join(c["source"])), None)
    assert class_cell is not None

    # 应有 if __name__ cell
    main_cell = next((c for c in cells if c["cell_type"] == "code" and '__main__' in "".join(c["source"])), None)
    assert main_cell is not None

    # kernelspec 元数据
    assert "kernelspec" in notebook.get("metadata", {})


def test_export_notebook_from_graph():
    """POST /api/export-notebook 从前端 graph 生成 notebook"""
    graph = {
        "nodes": [
            {"id": "input1", "data": {"nodeType": "input", "label": "Input", "params": {}}},
            {"id": "linear1", "data": {"nodeType": "linear", "label": "Linear", "params": {"in_features": 10, "out_features": 5}}},
            {"id": "output1", "data": {"nodeType": "output", "label": "Output", "params": {}}},
        ],
        "edges": [
            {"source": "input1", "target": "linear1", "sourceHandle": None, "targetHandle": "x"},
            {"source": "linear1", "target": "output1", "sourceHandle": None, "targetHandle": "x"},
        ],
    }
    response = client.post(
        "/api/export-notebook",
        json={
            "graph": graph,
            "filename": "graph_model",
            "training_config": None,
            "data_graph": None,
            "bindings": None,
        },
    )
    assert response.status_code == 200
    data = response.json()
    assert data["success"] is True
    assert data["filename"] == "graph_model.ipynb"
    assert data["mime_type"] == "application/x-ipynb+json"

    decoded = base64.b64decode(data["content"]).decode("utf-8")
    notebook = json.loads(decoded)
    code_cells = [c for c in notebook["cells"] if c["cell_type"] == "code"]
    all_source = "\n".join("".join(c["source"]) for c in code_cells)
    assert "class FlowHamsterModel" in all_source
    assert "nn.Linear" in all_source


def test_export_notebook_with_data_graph_and_bindings():
    """POST /api/export-notebook 支持 data_graph + bindings 追加 scaffold"""
    graph = {
        "nodes": [
            {"id": "input1", "data": {"nodeType": "input", "label": "Input", "params": {"name": "image"}}},
            {"id": "linear1", "data": {"nodeType": "linear", "label": "Linear", "params": {"in_features": 784, "out_features": 10}}},
            {"id": "output1", "data": {"nodeType": "output", "label": "Output", "params": {}}},
        ],
        "edges": [
            {"source": "input1", "target": "linear1", "sourceHandle": None, "targetHandle": "x"},
            {"source": "linear1", "target": "output1", "sourceHandle": None, "targetHandle": "x"},
        ],
    }
    data_graph = {
        "nodes": [
            {"id": "ds1", "data": {"nodeType": "csv_source", "label": "CSV", "params": {"path": "./data/train.csv"}}},
            {"id": "out1", "data": {"nodeType": "dataset_output", "label": "Output", "params": {"fields": "image,label"}}},
        ],
        "edges": [
            {"source": "ds1", "target": "out1", "sourceHandle": None, "targetHandle": "x"},
        ],
    }
    bindings = [
        {"target": "model_input", "targetKey": "image", "sourceGraph": "data", "sourceKey": "image"},
        {"target": "training_target", "sourceKey": "label"},
    ]
    response = client.post(
        "/api/export-notebook",
        json={
            "graph": graph,
            "filename": "workflow_model",
            "training_config": {"taskType": "classification", "loss": {"type": "cross_entropy", "enabled": True}, "optimizer": {"type": "adamw", "enabled": True, "params": {"lr": 0.001}}, "scheduler": {"type": "step_lr", "enabled": False}, "metrics": [], "runtime": {"device": "cpu", "epochs": 2, "batchSize": 32}, "checkpoint": {"enabled": False}},
            "data_graph": data_graph,
            "bindings": bindings,
        },
    )
    assert response.status_code == 200
    data = response.json()
    assert data["success"] is True

    decoded = base64.b64decode(data["content"]).decode("utf-8")
    notebook = json.loads(decoded)
    code_cells = [c for c in notebook["cells"] if c["cell_type"] == "code"]
    all_source = "\n".join("".join(c["source"]) for c in code_cells)
    assert "FlowHamsterDataset" in all_source or "BOUND_MODEL_INPUTS" in all_source


def test_export_invalid_format_fallback():
    """POST /api/export 未知 format 时默认按 py 处理"""
    response = client.post(
        "/api/export",
        json={
            "code": SAMPLE_CODE,
            "format": "unknown",
            "filename": "test",
        },
    )
    assert response.status_code == 200
    data = response.json()
    assert data["mime_type"] == "text/x-python"
    assert data["filename"] == "test.py"
